{
  "hash": "94608cd7b563125fffc05d8df76f84c9",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: Python basics\nformat: \n  html:\n    toc: true\n---\n\n## Arithmetic operators\n\nAt a minimum, we can use Python as a calculator.\nIf we type the following into a cell, and click the run button (the triangle-shaped button that looks like a play button), we will see the output under the cell.\nAnother quicker way to run the code in the selected cell is by pressing on your keyboard <kbd>Ctrl</kbd>+<kbd>Enter</kbd> (for Windows) or <kbd>Command</kbd>+<kbd>Return</kbd> (for MacOS).\n\n#### Addition\n\n::: {#daa0521f .cell execution_count=1}\n``` {.python .cell-code}\n2 + 3\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n5\n```\n:::\n:::\n\n\n#### Subtraction\n\n::: {#2d5e66cb .cell execution_count=2}\n``` {.python .cell-code}\n2 - 3\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\n-1\n```\n:::\n:::\n\n\n#### Multiplication\n\n::: {#48395089 .cell execution_count=3}\n``` {.python .cell-code}\n2 * 3\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n6\n```\n:::\n:::\n\n\n#### Division\n\n::: {#3340149f .cell execution_count=4}\n``` {.python .cell-code}\n2 / 3\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\n0.6666666666666666\n```\n:::\n:::\n\n\n#### Exponentiation\n\nOne thing that you might need to be a little careful about is the exponentiation. If you have used Microsoft Excel, MATLAB, R, or some other programming languages, the operator for exponentiation is the caret `^` symbol. Let’s take a look at if that works in Python.\n\n::: {#11af445b .cell execution_count=5}\n``` {.python .cell-code}\n2 ^ 3\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\n1\n```\n:::\n:::\n\n\nHmm. That’s not what we expected. It turns out in Python (and a few other languages), the caret symbol is used for another operation called bitwise exclusive OR.\nIn Python we use double asterisks `**` for exponentiation.\n\n::: {#6821c7fa .cell execution_count=6}\n``` {.python .cell-code}\n2 ** 3\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\n8\n```\n:::\n:::\n\n\n#### Order of operations\n\nWe can also use parentheses to specify what operations should be resolved first. For example, to convert 60 degrees Fahrenheit to Celsius, we can do:\n\n::: {#c19c78d2 .cell execution_count=7}\n``` {.python .cell-code}\n5 / 9 * (60 - 32)\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\n15.555555555555557\n```\n:::\n:::\n\n\n#### Assignment operator\n\nIn Python we can use a `=` symbol, which is called the assignment operator, to assign values on the right to objects on the left. \nLet’s assign a number to a variable called \"age\".\nWhen we run the cell, it seems nothing happened. \nBut that’s only because we didn’t ask Python to display anything in the output after the assignment operation. \nWe can call the Python built-in function print() to display information in the output.\nWe can also use another Python built-in function `type` to check the type of an object, in this case, the variable called \"age\". \nAnd we can see the type is \"int\", standing for integers.\n\n::: {#2a644646 .cell execution_count=8}\n``` {.python .cell-code}\nage = 26\nprint(age)\nprint(type(age))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n26\n<class 'int'>\n```\n:::\n:::\n\n\nLet’s create another variable called \"pi\", and assign it with a value of 3.1415. \nWe can see that this time the variable has a type of \"float\" for floating-point number, or a number with a decimal point.\n\n::: {#0d20093e .cell execution_count=9}\n``` {.python .cell-code}\npi = 3.1415\nprint(pi)\nprint(type(pi))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n3.1415\n<class 'float'>\n```\n:::\n:::\n\n\nWe can also assign string or text values to a variable. \nLet’s create a variable called \"name\", and assign it with a value \"Ben\".\n\n::: {#7c1bcffe .cell execution_count=10}\n``` {.python .cell-code}\nname = Ben\nprint(name)\n```\n\n::: {.cell-output .cell-output-error}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre><span class=\"ansi-red-fg\">---------------------------------------------------------------------------</span>\n<span class=\"ansi-red-fg\">NameError</span>                                 Traceback (most recent call last)\n<span class=\"ansi-cyan-fg\">Cell</span><span class=\"ansi-cyan-fg\"> </span><span class=\"ansi-green-fg\">In[10]</span><span class=\"ansi-green-fg\">, line 1</span>\n<span class=\"ansi-green-fg\">----&gt; </span><span class=\"ansi-green-fg\">1</span> name = <span class=\"ansi-yellow-bg\">Ben</span>\n<span class=\"ansi-green-fg\">      2</span> <span style=\"color:rgb(0,135,0)\">print</span>(name)\n\n<span class=\"ansi-red-fg\">NameError</span>: name 'Ben' is not defined</pre>\n```\n:::\n\n:::\n:::\n\n\nWe got an error message. \nAs it turns out, to make it work in Python we need to wrap any string values in quotation marks. We can use either single quotes `'` or double quotes `\"`. \nWe just need to use the same kind of quotes at the beginning and end of the string. \nYou do need to use the same kind of quotes at the beginning and end of the string. \nWe can also see that the variable has a type of \"str\", standing for strings.\n\n#### Single vs Double Quotes\n\nPython supports using either single quotes `'` or double quotes `\"` to specify strings. \nThere’s no set rules on which one you should use.\n- Some Python style guide suggests using single-quotes for shorter strings (the technical term is string literals), as they are a little easier to type and read, and using double-quotes for strings that are likely to contain single-quote characters as part of the string itself (such as strings containing natural language, e.g. \"I'll be there.\").\n- Some other Python style guide suggests being consistent with your choice of string quote character within a file. Pick `'` or `\"` and stick with it.\n\nAssigning values to objects\n\nTry to assign values to some objects and observe each object after you have assigned a new value. What do you notice?\n\n::: {#16cdc5c6 .cell execution_count=11}\n``` {.python .cell-code}\nname = \"Ben\"\nprint(name)\n\nname = \"Harry Potter\"\nprint(name)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBen\nHarry Potter\n```\n:::\n:::\n\n\nWhen we assign a value to an object, the object stores that value so we can access it later. \nHowever, if we store a new value in an object we have already created (like when we stored \"Harry Potter\" in the name object), it replaces the old value.\n\n#### Guidelines on naming objects\n\n- You want your object names to be explicit and not too long.\n- They cannot start with a number (2x is not valid, but x2 is).\n- Python is case sensitive, so for example, weight_kg is different from Weight_kg.\n- You cannot use spaces in the name.\n- There are some names that cannot be used because they are the names of fundamental functions in Python (e.g., if, else, `for; run help(\"keywords\") for a complete list). You may also notice these keywords change to a different color once you type them (a feature called “syntax highlighting”).\n- It’s best to avoid dots (.) within names. Dots have a special meaning (methods) in Python and other programming languages.\n- It is recommended to use nouns for object names and verbs for function names.\n- Be consistent in the styling of your code, such as where you put spaces, how you name objects, etc. Using a consistent coding style makes your code clearer to read for your future self and your collaborators. The official Python naming conventions can be found [here](https://peps.python.org/pep-0008/#naming-conventions).\n\n#### Exercise: Bad names for objects\n\nTry to assign values to some new objects. What do you notice? \nAfter running all four lines of code bellow, what value do you think the object `Flower` holds?\n\n::: {#7bb877fc .cell execution_count=12}\n``` {.python .cell-code}\n1number = 3\n```\n\n::: {.cell-output .cell-output-error}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre>  <span class=\"ansi-cyan-fg\">Cell</span><span class=\"ansi-cyan-fg\"> </span><span class=\"ansi-green-fg\">In[12]</span><span class=\"ansi-green-fg\">, line 1</span>\n<span class=\"ansi-red-fg\">    </span><span class=\"ansi-red-fg\">1number = 3</span>\n    ^\n<span class=\"ansi-red-fg\">SyntaxError</span><span class=\"ansi-red-fg\">:</span> invalid decimal literal\n</pre>\n```\n:::\n\n:::\n:::\n\n\n::: {#b6557ef6 .cell execution_count=13}\n``` {.python .cell-code}\nfavorite number = 12\n```\n\n::: {.cell-output .cell-output-error}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre>  <span class=\"ansi-cyan-fg\">Cell</span><span class=\"ansi-cyan-fg\"> </span><span class=\"ansi-green-fg\">In[13]</span><span class=\"ansi-green-fg\">, line 1</span>\n<span class=\"ansi-red-fg\">    </span><span class=\"ansi-red-fg\">favorite number = 12</span>\n             ^\n<span class=\"ansi-red-fg\">SyntaxError</span><span class=\"ansi-red-fg\">:</span> invalid syntax\n</pre>\n```\n:::\n\n:::\n:::\n\n\nNotice that we get an error when we try to assign values to `1number` and `favorite number`. \nThis is because we cannot start an object name with a numeral and we cannot have spaces in object names. \n\n::: {#674a2234 .cell execution_count=14}\n``` {.python .cell-code}\nFlower = \"marigold\"\nflower = \"rose\"\n\nprint(Flower)\nprint(flower)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmarigold\nrose\n```\n:::\n:::\n\n\nThe object `Flower` still holds “marigold.” This is because Python is case-sensitive, so running `flower = \"rose\"` does NOT change the `Flower` object. \nThis can get confusing, and is why we generally avoid having objects with the same name and different capitalization.\n\n## Data structures\n\n### Python list\n\nRather than storing a single value to an object, we can also store multiple values into a single object called a list. \nA Python list is indicated with a pair of square brackets `[]`, and different items are separated by a comma. \nFor example, we can have a list of numbers, or a list of strings.\n\n::: {#39902f78 .cell execution_count=15}\n``` {.python .cell-code}\nsquares = [1, 4, 9, 16, 25]\nprint(squares)\n\nnames = [\"Sara\", \"Tom\", \"Jerry\", \"Emma\"]\nprint(names)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1, 4, 9, 16, 25]\n['Sara', 'Tom', 'Jerry', 'Emma']\n```\n:::\n:::\n\n\nWe can also check the type of the object by calling the built-in `type` function.\n\n::: {#a5e1ef95 .cell execution_count=16}\n``` {.python .cell-code}\ntype(names)\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```\nlist\n```\n:::\n:::\n\n\nAn item from a list can be accessed by its position using the square bracket notation. \nSay if we want to get the first name, \"Sara\", from the list, we can do\n\n::: {#ba0e26b6 .cell execution_count=17}\n``` {.python .cell-code}\nnames[1]\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```\n'Tom'\n```\n:::\n:::\n\n\nThat’s not what we expected. \nPython uses something called 0-based indexing. \nIn other words, it starts counting from 0 rather than 1. \nIf we want to get the first item from the list, we should use an index of 0. \nLet's try that.\n\n::: {#37e28da6 .cell execution_count=18}\n``` {.python .cell-code}\nnames[0]\n```\n\n::: {.cell-output .cell-output-display execution_count=18}\n```\n'Sara'\n```\n:::\n:::\n\n\nNow see if you can get the *last* name from the list.\n\n::: {#88d3b8f9 .cell execution_count=19}\n``` {.python .cell-code}\nnames[3]\n```\n\n::: {.cell-output .cell-output-display execution_count=19}\n```\n'Emma'\n```\n:::\n:::\n\n\nA cool feature in Python is it also supports negative indexing. \nIf we just want the last time on a list, we can pass the index of `-1`.\n\n::: {#adc2b33a .cell execution_count=20}\n``` {.python .cell-code}\nnames[-1]\n```\n\n::: {.cell-output .cell-output-display execution_count=20}\n```\n'Emma'\n```\n:::\n:::\n\n\n### Python dictionaries\n\nPython lists allow us to organize items by their position. \nSometimes we want to organize items by their \"keys\". \nThis is when a Python dictionary comes in handy.\n\nA Python dictionary is indicated with a pair of curly brackets `{}` and composed of entries of key-value pairs. \nThe key and value are connected via a colon `:`, and different entries are separated by a comma `,`. \nFor example, let’s create a dictionary of capitals. \nWe can separate the entries in multiple lines to make it a little easier to read, especially when we have many entries. In Python we can break lines inside braces (e.g., `()`, `[]`, `{}`) without breaking the code. \nThis is a common technique people use to avoid long lines and make their code more readable.\n\n::: {#22da3ce0 .cell execution_count=21}\n``` {.python .cell-code}\ncapitals = {\"France\": \"Paris\",\n            \"USA\": \"Washington DC\",\n            \"Germany\": \"Berlin\",\n            \"Canada\": \"Ottawa\"}\n```\n:::\n\n\nWe can check the type of the object by calling the built-in `type` function.\n\n::: {#e24dd282 .cell execution_count=22}\n``` {.python .cell-code}\ntype(capitals)\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```\ndict\n```\n:::\n:::\n\n\nAn entry from a dictionary can be accessed by its key using the square bracket notation. \nSay if we want to get the capital for USA, , we can do\n\n::: {#ec3440d6 .cell execution_count=23}\n``` {.python .cell-code}\ncapitals['USA']\n```\n\n::: {.cell-output .cell-output-display execution_count=23}\n```\n'Washington DC'\n```\n:::\n:::\n\n\nNow see if you can get the capital from another country.\n\n::: {#16c41e7a .cell execution_count=24}\n``` {.python .cell-code}\ncapitals[\"Canada\"]\n```\n\n::: {.cell-output .cell-output-display execution_count=24}\n```\n'Ottawa'\n```\n:::\n:::\n\n\n## Calling functions\n\nSo far we have used two Python built-in functions, `print` to print some values on the screen, and `type` to show the type of an object. \nThe way we called these functions is to first type the name of the function, followed by a pair of parenthesis. \nMany functions require additional pieces of information to do their job. \nWe call these additional values \"arguments\" or \"parameters\". \nWe pass the arguments to a function by placing values in between the parenthesis. \nA function takes in these arguments and does a bunch of \"magic\" behind the scenes to output something we're interested in.\n\nDo all functions need arguments? Let's test some other functions.\nIt is common that we may want to use a function from a module. \nIn this case we will need to first import the module to our Python session. \nWe do that by using the import keyword followed by the module's name. \nTo call a function from a module, we type the name of the imported module, followed by a dot `.`, followed by the name of the function that we wish to call.\n\nBelow we import the operating system module and call the function `getcwd` to get the current working directory.\n\n::: {#da827566 .cell execution_count=25}\n``` {.python .cell-code}\nimport os\nos.getcwd()\n```\n\n::: {.cell-output .cell-output-display execution_count=25}\n```\n'/Users/fredfeng/Desktop/teaching/short-courses/carpentries/curricula/um-carpentries-python-dev'\n```\n:::\n:::\n\n\nSometimes the function resides inside a submodule, we can specify the submodule using the dot notation. \nIn the example below, we call the `today` function which is located in the date submodule inside the datetime module that we imported.\n\n::: {#0b727b83 .cell execution_count=26}\n``` {.python .cell-code}\nimport datetime\ndatetime.date.today()\n```\n\n::: {.cell-output .cell-output-display execution_count=26}\n```\ndatetime.date(2026, 2, 26)\n```\n:::\n:::\n\n\nWhile some functions, like those above, don't need any arguments, in other functions we may want to use multiple arguments. \nWhen we are using multiple arguments, we separate the arguments with commas. \nFor example, we can use the `print` function to print two strings:\n\n::: {#e557b0ef .cell execution_count=27}\n``` {.python .cell-code}\nprint(\"My name is\", name)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMy name is Harry Potter\n```\n:::\n:::\n\n\nPro-tip:\n\nEach function has a help page that documents what a function does, what arguments it expects and what it will return. \nYou can bring up the help page a few different ways. You can type `?` followed by the function name, for example, `?print`, A help document should pop up.\nYou can also place the mouse curse next to a function, and press <kbd>Shift</kbd>+<kbd>Tab</kbd> to see its help doc.\n\n\n#### Learning more about functions\n\nLook up the function `round`. \nWhat does it do? What will you get as output for the following lines of code?\n\n::: {#b02958c6 .cell execution_count=28}\n``` {.python .cell-code}\nround(3.1415)\nround(3.1415, 3)\n```\n\n::: {.cell-output .cell-output-display execution_count=28}\n```\n3.142\n```\n:::\n:::\n\n\nThe `round` function rounds a number to a given precision. \nBy default, it rounds the number to an integer (in our example above, to 3). \nIf you give it a second number, it rounds it to that number of digits (in our example above, to 3.142)\n\n#### Position of the arguments in functions\n\nWhich of the following lines of code will give you an output of 3.14? \nFor the one(s) that don't give you 3.14, what do they give you?\n\n::: {#ed867f16 .cell execution_count=29}\n``` {.python .cell-code}\nround(number=3.1415)\n```\n\n::: {.cell-output .cell-output-display execution_count=29}\n```\n3\n```\n:::\n:::\n\n\n::: {#308648e9 .cell execution_count=30}\n``` {.python .cell-code}\nround(number=3.1415, ndigits=2)\n```\n\n::: {.cell-output .cell-output-display execution_count=30}\n```\n3.14\n```\n:::\n:::\n\n\n::: {#dd53d81b .cell execution_count=31}\n``` {.python .cell-code}\nround(ndigits=2, number=3.1415)\n```\n\n::: {.cell-output .cell-output-display execution_count=31}\n```\n3.14\n```\n:::\n:::\n\n\n::: {#78f8671a .cell execution_count=32}\n``` {.python .cell-code}\nround(2, 3.1415)\n```\n\n::: {.cell-output .cell-output-error}\n\n::: {.ansi-escaped-output}\n```{=html}\n<pre><span class=\"ansi-red-fg\">---------------------------------------------------------------------------</span>\n<span class=\"ansi-red-fg\">TypeError</span>                                 Traceback (most recent call last)\n<span class=\"ansi-cyan-fg\">Cell</span><span class=\"ansi-cyan-fg\"> </span><span class=\"ansi-green-fg\">In[32]</span><span class=\"ansi-green-fg\">, line 1</span>\n<span class=\"ansi-green-fg\">----&gt; </span><span class=\"ansi-green-fg\">1</span> <span style=\"color:rgb(0,135,0)\" class=\"ansi-yellow-bg\">round</span><span class=\"ansi-yellow-bg\">(</span><span class=\"ansi-green-fg ansi-yellow-bg\">2</span><span class=\"ansi-yellow-bg\">,</span><span class=\"ansi-yellow-bg\"> </span><span class=\"ansi-green-fg ansi-yellow-bg\">3.1415</span><span class=\"ansi-yellow-bg\">)</span>\n\n<span class=\"ansi-red-fg\">TypeError</span>: 'float' object cannot be interpreted as an integer</pre>\n```\n:::\n\n:::\n:::\n\n\nThe 2nd and 3rd lines will give you the right answer because the arguments are named, and when you use names the order doesn't matter. \nThe 1st line will give you 3 because the default number of digits is 0. \nThen 4th line will give you 2 because, since you didn't name the arguments, `x=2` and `digits=3.1415`.\n\nSometimes it is helpful - or even necessary - to include the argument name, but often we can skip the argument name, if the argument values are passed in a certain order. \nIf all this function stuff sounds confusing, don't worry! We will see a bunch of examples as we go that will make things clearer.\n\n### Comments\n\nSometimes we may want to write some comments in our code to help us remember what our code is doing, but we don't want Python to think these comments are a part of the code you want to evaluate. \nThat’s where comments come in. \nAnything after a `#` sign in your code will be ignored by Python. \nFor example, let's say we wanted to make a note of what each of the functions we just used do:\n\n::: {#01c44ebd .cell execution_count=33}\n``` {.python .cell-code}\ndatetime.date.today()   # returns today's date\n```\n\n::: {.cell-output .cell-output-display execution_count=33}\n```\ndatetime.date(2026, 2, 26)\n```\n:::\n:::\n\n\n::: {#81c5d2a4 .cell execution_count=34}\n``` {.python .cell-code}\nos.getcwd()    # returns our current working directory\n```\n\n::: {.cell-output .cell-output-display execution_count=34}\n```\n'/Users/fredfeng/Desktop/teaching/short-courses/carpentries/curricula/um-carpentries-python-dev'\n```\n:::\n:::\n\n\nSome other time we may want to temporarily disable some code without deleting them. We can comment out lines of code by placing a `#` sign at the beginning of each line.\n\nA handy keyboard shortcut for that is move the mouse cursor to the line you wish to comment out, then press <kbd>Ctrl</kbd>+<kbd>/</kbd> (for Windows) or <kbd>Command</kbd>+<kbd>/</kbd> (for MacOS) to toggle through comment and uncomment. If you wish to comment out multiple lines, first select all the lines, then use the same keyboard shortcut to comment or uncomment.\n\n",
    "supporting": [
      "python-basics_files"
    ],
    "filters": [],
    "includes": {}
  }
}